// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_ddu13yraB5A8rTrma_9rGYeCARLpLZM',
    appId: '1:839899581403:web:f9c3cf6c007b2263cff5fe',
    messagingSenderId: '839899581403',
    projectId: 'new-flutter-learning-d83d0',
    authDomain: 'new-flutter-learning-d83d0.firebaseapp.com',
    storageBucket: 'new-flutter-learning-d83d0.appspot.com',
    measurementId: 'G-P0NW6VS4R1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1m7qQ7Pcu1mgnzk_pDYD5Czir_KWY4vo',
    appId: '1:839899581403:android:55db955393c84847cff5fe',
    messagingSenderId: '839899581403',
    projectId: 'new-flutter-learning-d83d0',
    storageBucket: 'new-flutter-learning-d83d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApO3Zcng6EJE-G3PIFNK9pYmxdZ7jPy4Y',
    appId: '1:839899581403:ios:e1680b40414882decff5fe',
    messagingSenderId: '839899581403',
    projectId: 'new-flutter-learning-d83d0',
    storageBucket: 'new-flutter-learning-d83d0.appspot.com',
    androidClientId: '839899581403-f41tc346nl3pkcse8vs1fkqfds7nn5os.apps.googleusercontent.com',
    iosClientId: '839899581403-90j64h0n7ps0msn1omlqel2a6vd4b779.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceUi1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApO3Zcng6EJE-G3PIFNK9pYmxdZ7jPy4Y',
    appId: '1:839899581403:ios:9b9673f478ccc38dcff5fe',
    messagingSenderId: '839899581403',
    projectId: 'new-flutter-learning-d83d0',
    storageBucket: 'new-flutter-learning-d83d0.appspot.com',
    androidClientId: '839899581403-f41tc346nl3pkcse8vs1fkqfds7nn5os.apps.googleusercontent.com',
    iosClientId: '839899581403-7ambgn7it6q82sdvlank8vaedqvcu7f8.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceUi1.RunnerTests',
  );
}
